#ifndef ___LIBIM_STATUS__H__
#define ___LIBIM_STATUS__H__

typedef enum {
	LIBIM_STATUS_ERROR = -1,
	LIBIM_STATUS_OFFLINE = 0,
	LIBIM_STATUS_AVAILABLE,
	LIBIM_STATUS_INVISIBLE,
	LIBIM_STATUS_AWAY,
	LIBIM_STATUS_EXTENED_AWAY,
	LIBIM_STATUS_DND
} im_status;

#endif